title: Carl Cederborg
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
  Technical Portfolio
  <br><br>
  <a href="https://www.linkedin.com/in/carl-cederborg-9b9504187/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
